### ISSUE TITLE
ZERODCE_SDAG预训练模型问题

### ISSUE THREAD

**Issue by msm8976** [zheng980629/SDAG#1]
你好，请问仓库中的[ZERODCE_SDAG.pth](https://github.com/zheng980629/SDAG/blob/master/pretrained_model/ZERODCE_SDAG.pth)预训练模型是可以直接应用于[Zero-DCE](https://github.com/Li-Chongyi/Zero-DCE)吗，是否需要进行其他操作。我使用lowlight_test输出的图像不仅没有增亮，反而大部分全为黑色，少部分在黑色外还包含错误的颜色：
![0002_c1s1_000451_03](https://github.com/zheng980629/SDAG/assets/32473245/d991ee03-7abc-44c3-b432-69e855d75f2a)
![0022_c6s1_002926_01](https://github.com/zheng980629/SDAG/assets/32473245/1bf78232-779a-438e-8fa1-ae0cc8e75af4)

**Comment by zheng980629** [comment]
很抱歉，我们在上传了错误的预训练模型，现已更新。该模型可以直接应用于Zero-DCE。
对于背景为完全黑色（0）的的输入图像，ZeroDCE没有办法进行增强，因为该模型的曲线建模方式本质上是对像素强度的拉伸放大，而值为0的像素是没办法进行拉伸的。
